

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
     
      <body>
      <h1>This is Main Layout</h1>
        {children}</body>
    </html>
  );
}
